### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jabedzaman** [tr1ckydev/spotifly#1]
{"data":{"trackUnion":{"__typename":"GenericError"}},"extensions":{"cacheControl":{"version":1,"hints":[]}}}

**Comment by tr1ckydev** [comment]
Can you please provide more information? 
1. Which function? 
2. What's the data you are passing through it?

**Comment by jabedzaman** [comment]
Sorry for not being precise... Okay so I was using it with nodejs and tsup... When I am trying to call the function to search for album its giving this error....

My tsup config:

``` 
export default defineConfig({
  clean: !isDev,
  dts: !isDev,
  entry: ["src/index.ts"],
  format: ["esm"],
  minify: !isDev,
  metafile: !isDev,
  sourcemap: true,
  target: "esnext",
  outDir: "dist",
  onSuccess: isDev ? "node dist/index.mjs" : undefined,
});
```

Kinda confused if that was typescript error... but when i cloned the repo and used the build it works fine

**Comment by jabedzaman** [comment]
I have set the type to module and after that it complains like this:

```
🚧  Running in development mode
CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.7.0
CLI Using tsup config: /home/jabed/Devs/spotify/tsup.config.ts
CLI Running in watch mode
CLI Target: esnext
ESM Build start
ESM dist/index.js     177.00 B
ESM dist/index.js.map 331.00 B
ESM ⚡️ Build success in 5ms
CLI Watching for changes in "."
CLI Ignoring changes in "**/{.git,node_modules}/**" | "dist"
WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: No token provided.
    at _toError (/home/jabed/Devs/spotify/node_modules/.pnpm/spotify-web-api-node@5.0.2/node_modules/spotify-web-api-node/src/http-manager.js:39:12)
    at /home/jabed/Devs/spotify/node_modules/.pnpm/spotify-web-api-node@5.0.2/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/home/jabed/Devs/spotify/node_modules/.pnpm/superagent@6.1.0/node_modules/superagent/lib/node/index.js:905:3)
    at /home/jabed/Devs/spotify/node_modules/.pnpm/superagent@6.1.0/node_modules/superagent/lib/node/index.js:1127:20
    at IncomingMessage.<anonymous> (/home/jabed/Devs/spotify/node_modules/.pnpm/superagent@6.1.0/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at Stream.emit (node:events:513:28)
    at Unzip.<anonymous> (/home/jabed/Devs/spotify/node_modules/.pnpm/superagent@6.1.0/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  body: { error: { status: 401, message: 'No token provided' } },
  headers: {
    'www-authenticate': 'Bearer realm="spotify"',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
    'access-control-allow-credentials': 'true',
    'access-control-max-age': '604800',
    'content-type': 'application/json',
    'content-encoding': 'gzip',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    date: 'Thu, 11 May 2023 05:34:23 GMT',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 401
}
``` 

Node v : 18
OS : arch linux

**Comment by jabedzaman** [comment]
Tried with `.mjs` 

![image](https://github.com/tr1ckydev/spotifly/assets/99767817/7113a6e9-7c63-426d-aab4-1a2cc73bb4d0)

**Comment by tr1ckydev** [comment]
I can't find `spotifly` in the error stack rather the problem is with your `spotify-web-api-node` which is a different package.
Also, getTrack only works with track ids. To search use [searchTracks](https://github.com/tr1ckydev/spotifly#searchtracksterms-string-limit-number-promisespotifysearchtracks).
Please read the documentation carefully (https://github.com/tr1ckydev/spotifly#-documentation).
Let me know if I can help you with anything else.

**Comment by jabedzaman** [comment]
FFF!!!!!!!!!!!! Srry buddy I was just being dumb from yesterday night... I apolozise...  And got my problem solved also...
